version: '3.0'
services:
    app:
        container_name: todo_api
        build: .
        ports:
            - "3000:3000"
        environment:
            - DATABASE_URL="postgresql://postgres:todo_api@localhost:5432/tododb?schema=public"
        depends_on:
            - todo_db
        networks:
            - todo_network
    todo_db:
        container_name: todo_db
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=todo_api
            - POSTGRES_DB=tododb
        ports:
            - "5432:5432"
        volumes:
            - todo_db_data:/var/lib/postgresql/data
        networks:
            - todo_network
networks:
    todo_network:
        driver: bridge

volumes:
    todo_db_data: